AlkOutlet_urls = [
            "https://alkoutlet.lv/alus-sidri-kokteili/alus.html",
            "https://alkoutlet.lv/bezalkoholiskie/bezalkoholiskie-vermuts.html",
            "https://alkoutlet.lv/bezalkoholiskie/energijas-dzerieni.html",
            "https://alkoutlet.lv/bezalkoholiskie/ledus-teja.html",
            "https://alkoutlet.lv/bezalkoholiskie/limonade.html",
            "https://alkoutlet.lv/bezalkoholiskie/sula-nektars-smutiji.html",
            "https://alkoutlet.lv/bezalkoholiskie/uden-s-mineraludens.html",
            "https://alkoutlet.lv/stiprie/balzams.html",
            "https://alkoutlet.lv/stiprie/degvins.html",
            "https://alkoutlet.lv/stiprie/dzins.html",
            "https://alkoutlet.lv/stiprie/kalvadoss.html",
            "https://alkoutlet.lv/stiprie/konjaks.html",
            "https://alkoutlet.lv/stiprie/likieris.html",
            "https://alkoutlet.lv/stiprie/rums.html",
            "https://alkoutlet.lv/stiprie/tekila.html",
            "https://alkoutlet.lv/stiprie/uzlejumi.html",
            "https://alkoutlet.lv/stiprie/viskijs.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/baltvins.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/dzirkstosais-vins.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/roza-vins.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/sampanietis.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/sarkanvins.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/stiprinats-vins.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/vermuts.html",]
rimi_urls = [
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/dzirkstosie-bezalkoholiskie-dzerieni/c/SH-5-2",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/sporta-un-funkcionalie-dzerieni/c/SH-5-7",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/limonades/c/SH-5-4",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/sulas-un-sulu-dzerieni/c/SH-5-8",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/svaigas-sulas-un-smutiji/c/SH-5-11",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/sirupi/c/SH-5-6",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/bezalkoholiskais-alus-sidri-un-vini/c/SH-5-1",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/dzirkstosie-bezalkoholiskie-dzerieni/c/SH-5-2",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/energijas-dzerieni/c/SH-5-3",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/baltvins/c/SH-1-2-1",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/sarkanvins/c/SH-1-2-2",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/roza-vins/c/SH-1-2-3",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/auglu-vins/c/SH-1-2-4",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/stiprinats-vini/c/SH-1-2-5",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/dzirkstosais-vins/c/SH-1-5-1",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/sampanietis/c/SH-1-5-2",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/alus/c/SH-1-12",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/sidrs/c/SH-1-14",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/kokteili/c/SH-1-13",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/degvini/c/SH-1-3",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/tekila/c/SH-1-15",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/dzins/c/SH-1-10",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/brendijs/c/SH-1-6",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/viskijs/c/SH-1-7",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/konjaks/c/SH-1-8",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/rums/c/SH-1-9",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/balzams/c/SH-1-11",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/likieris/c/SH-1-1",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/vermuts/c/SH-1-4",]
SandWine_urls = [
            "https://www.spiritsandwine.lv/lv/absints?page=1",
            "https://www.spiritsandwine.lv/lv/alus-alk?page=1",
            "https://www.spiritsandwine.lv/lv/alus-bezalk?page=1",
            "https://www.spiritsandwine.lv/lv/armanjaks?page=1",
            "https://www.spiritsandwine.lv/lv/bag-in-box-baltivins?page=1",
            "https://www.spiritsandwine.lv/lv/bag-in-box-sarkanvins?page=1",
            "https://www.spiritsandwine.lv/lv/bag-in-box-sartvins?page=1",
            "https://www.spiritsandwine.lv/lv/baltvins?page=1",
            "https://www.spiritsandwine.lv/lv/bezalkaholiskais-vins?page=1",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskais-dzirkstosais-vins?page=1",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskais-sidrs?page=1",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskie-dzerieni?page=1",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskie-kokteili?page=1",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskie-stiprie-dzerieni?page=1",
            "https://www.spiritsandwine.lv/lv/brendijs?page=1",
            "https://www.spiritsandwine.lv/lv/degvins?page=1",
            "https://www.spiritsandwine.lv/lv/dzins?page=1",
            "https://www.spiritsandwine.lv/lv/dzirkstosais-vins?page=1",
            "https://www.spiritsandwine.lv/lv/energijas-dzerieni?page=1",
            "https://www.spiritsandwine.lv/lv/kalvadoss?page=1",
            "https://www.spiritsandwine.lv/lv/karstvini-karstie-dzerieni?page=1",
            "https://www.spiritsandwine.lv/lv/kokteili?page=1",
            "https://www.spiritsandwine.lv/lv/konjaks?page=1",
            "https://www.spiritsandwine.lv/lv/likieris?page=1",
            "https://www.spiritsandwine.lv/lv/mini?page=1",
            "https://www.spiritsandwine.lv/lv/rums?page=1",
            "https://www.spiritsandwine.lv/lv/sampanietis?page=1",
            "https://www.spiritsandwine.lv/lv/sarkanvins?page=1",
            "https://www.spiritsandwine.lv/lv/sartvins?page=1",
            "https://www.spiritsandwine.lv/lv/sidrs?page=1",
            "https://www.spiritsandwine.lv/lv/sirupi?page=1",
            "https://www.spiritsandwine.lv/lv/stiprinats-vins?page=1",
            "https://www.spiritsandwine.lv/lv/sula?page=1",
            "https://www.spiritsandwine.lv/lv/tekila?page=1",
            "https://www.spiritsandwine.lv/lv/udens?page=1",
            "https://www.spiritsandwine.lv/lv/uzlejums?page=1",
            "https://www.spiritsandwine.lv/lv/vermuts?page=1",
            "https://www.spiritsandwine.lv/lv/viskijs?page=1",]
LB_urls = [
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/sparkling-wine",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/champagne",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/baltvins",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/sarkanvins",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/roza-vins",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/karstvins",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/portvins",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/bag-in-box-wine",
            "https://www.lbveikali.lv/lv/alus-sidrs-un-kokteili/alus",
            "https://www.lbveikali.lv/lv/alus-sidrs-un-kokteili/sidrs",
            "https://www.lbveikali.lv/lv/alus-sidrs-un-kokteili/kokteili",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/dzins",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/rums",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/tekila",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/meskals",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/liqueur",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/spiritiniai-gerimai",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/viskijs",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/brendijs",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/konjaks",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/degvins",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/balsam",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/udens",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/juice",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/carbonated-soft-drinks",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/energijas-dzerieni",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/bezalkoholiskie-dzirkstosie-vini",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/bezalkoholiskais-alus",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/bezalkoholiskais-kokteilis",]
words_to_remove = [
            'Alk.', 'Alko.', 'Alkoh.', 'Alkohol.', 'Alkoholi', 'Alkoholiskais', 
            'Alkoholiskias', 'Alkoholisks', 'Alus', 'Armanjaks', 'Arom.', 'B.', 
            'Baltv.', 'Baltvīns', 'Bezalk.', 'Brendijs', 'Dabīgais', 'Degv.', 
            'Dz.', 'Dzirkst.', 'Dzēriens', 'Džins', 'Enerģijas', 'Gāz.', 'Gāzēts', 
            'Karstvīns', 'Konjaks', 'Liķieris', 'Minerālūdens', 'Rozā', 'Rums', 
            'S.', 'Sark.', 'Sarkanv.', 'Sidrs', 'Stiprs', 'Tekila', 'Vermuts', 
            'Viegli', 'Viskijs', 'alk.', 'dz.', 'dzē.', 'dzēr.', 'dzēriens', 'k.', 
            'kok.', 'kokt.', 'kokteil.', 'kokteilis', 'minerālūd.', 'v.', 'vīns', 
            'Šampanietis', 'Ūdens']
