AlkOutlet_urls = [
            "https://alkoutlet.lv/alus-sidri-kokteili/alus.html",
            "https://alkoutlet.lv/bezalkoholiskie/bezalkoholiskie-vermuts.html",
            "https://alkoutlet.lv/bezalkoholiskie/energijas-dzerieni.html",
            "https://alkoutlet.lv/bezalkoholiskie/ledus-teja.html",
            "https://alkoutlet.lv/bezalkoholiskie/limonade.html",
            "https://alkoutlet.lv/bezalkoholiskie/sula-nektars-smutiji.html",
            "https://alkoutlet.lv/bezalkoholiskie/uden-s-mineraludens.html",
            "https://alkoutlet.lv/stiprie/balzams.html",
            "https://alkoutlet.lv/stiprie/degvins.html",
            "https://alkoutlet.lv/stiprie/dzins.html",
            "https://alkoutlet.lv/stiprie/kalvadoss.html",
            "https://alkoutlet.lv/stiprie/konjaks.html",
            "https://alkoutlet.lv/stiprie/likieris.html",
            "https://alkoutlet.lv/stiprie/rums.html",
            "https://alkoutlet.lv/stiprie/tekila.html",
            "https://alkoutlet.lv/stiprie/uzlejumi.html",
            "https://alkoutlet.lv/stiprie/viskijs.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/baltvins.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/dzirkstosais-vins.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/roza-vins.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/sampanietis.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/sarkanvins.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/stiprinats-vins.html",
            "https://alkoutlet.lv/vins-un-vina-dzerieni/vermuts.html",]
rimi_urls = [
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/dzirkstosie-bezalkoholiskie-dzerieni/c/SH-5-2",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/sporta-un-funkcionalie-dzerieni/c/SH-5-7",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/limonades/c/SH-5-4",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/sulas-un-sulu-dzerieni/c/SH-5-8",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/svaigas-sulas-un-smutiji/c/SH-5-11",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/sirupi/c/SH-5-6",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/dzirkstosie-bezalkoholiskie-dzerieni/c/SH-5-2",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/energijas-dzerieni/c/SH-5-3",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/baltvins/c/SH-1-2-1",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/sarkanvins/c/SH-1-2-2",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/roza-vins/c/SH-1-2-3",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/auglu-vins/c/SH-1-2-4",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/stiprinats-vini/c/SH-1-2-5",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/dzirkstosais-vins/c/SH-1-5-1",
            "https://www.rimi.lv/e-veikals/lv/produkti/vina-darzs/sampanietis/c/SH-1-5-2",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/alus/c/SH-1-12",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/sidrs/c/SH-1-14",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/kokteili/c/SH-1-13",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/degvini/c/SH-1-3",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/tekila/c/SH-1-15",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/dzins/c/SH-1-10",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/brendijs/c/SH-1-6",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/viskijs/c/SH-1-7",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/konjaks/c/SH-1-8",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/rums/c/SH-1-9",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/balzams/c/SH-1-11",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/likieris/c/SH-1-1",
            "https://www.rimi.lv/e-veikals/lv/produkti/alkoholiskie-dzerieni/vermuts/c/SH-1-4",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/bezalkoholiskais-dzerieni/bezalkoholiskais-sidrs/c/SH-5-1-2",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/bezalkoholiskais-dzerieni/bezalkoholiskais-vins/c/SH-5-1-3",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/bezalkoholiskais-dzerieni/bezalkoholiskais-alus/c/SH-5-1-1",
            "https://www.rimi.lv/e-veikals/lv/produkti/dzerieni/bezalkoholiskais-dzerieni/bezalkoholiskie-kokteili/c/SH-5-1-4",]
SandWine_urls = [
            "https://www.spiritsandwine.lv/lv/absints",
            "https://www.spiritsandwine.lv/lv/alus-alk",
            "https://www.spiritsandwine.lv/lv/alus-bezalk",
            "https://www.spiritsandwine.lv/lv/armanjaks",
            "https://www.spiritsandwine.lv/lv/bag-in-box-baltvins",
            "https://www.spiritsandwine.lv/lv/bag-in-box-sarkanvins",
            "https://www.spiritsandwine.lv/lv/bag-in-box-sartvins",
            "https://www.spiritsandwine.lv/lv/baltvins",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskais-dzirkstosais-vins",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskais-sidrs",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskais-vins",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskie-dzerieni",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskie-kokteili",
            "https://www.spiritsandwine.lv/lv/bezalkoholiskie-stiprie-dzerieni",
            "https://www.spiritsandwine.lv/lv/brendijs",
            "https://www.spiritsandwine.lv/lv/degvins",
            "https://www.spiritsandwine.lv/lv/dzins",
            "https://www.spiritsandwine.lv/lv/dzirkstosais-vins",
            "https://www.spiritsandwine.lv/lv/energijas-dzerieni",
            "https://www.spiritsandwine.lv/lv/grappa",
            "https://www.spiritsandwine.lv/lv/kalvadoss",
            "https://www.spiritsandwine.lv/lv/karstvini-karstie-dzerieni",
            "https://www.spiritsandwine.lv/lv/konjaks",
            "https://www.spiritsandwine.lv/lv/likieris",
            "https://www.spiritsandwine.lv/lv/mini",
            "https://www.spiritsandwine.lv/lv/rums",
            "https://www.spiritsandwine.lv/lv/sampanietis",
            "https://www.spiritsandwine.lv/lv/sarkanvins",
            "https://www.spiritsandwine.lv/lv/sartvins",
            "https://www.spiritsandwine.lv/lv/sidrs",
            "https://www.spiritsandwine.lv/lv/sirupi",
            "https://www.spiritsandwine.lv/lv/stiprinats-vins",
            "https://www.spiritsandwine.lv/lv/sula",
            "https://www.spiritsandwine.lv/lv/tekila",
            "https://www.spiritsandwine.lv/lv/udens",
            "https://www.spiritsandwine.lv/lv/uzlejums",
            "https://www.spiritsandwine.lv/lv/vermuts",
            "https://www.spiritsandwine.lv/lv/viskijs",]
LB_urls = [
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/sparkling-wine",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/champagne",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/baltvins",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/sarkanvins",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/roza-vins",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/karstvins",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/portvins",
            "https://www.lbveikali.lv/lv/vins-un-dzirkstosie/bag-in-box-wine",
            "https://www.lbveikali.lv/lv/alus-sidrs-un-kokteili/alus",
            "https://www.lbveikali.lv/lv/alus-sidrs-un-kokteili/sidrs",
            "https://www.lbveikali.lv/lv/alus-sidrs-un-kokteili/kokteili",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/dzins",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/rums",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/tekila",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/meskals",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/liqueur",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/spiritiniai-gerimai",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/viskijs",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/brendijs",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/konjaks",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/degvins",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/balsam",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/udens",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/juice",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/carbonated-soft-drinks",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/energijas-dzerieni",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/bezalkoholiskie-dzirkstosie-vini",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/bezalkoholiskais-alus",
            "https://www.lbveikali.lv/lv/bezalkoholiskie-dzerieni-limonades/bezalkoholiskais-kokteilis",
            "https://www.lbveikali.lv/lv/stiprie-dzerieni/spiritiniai-gerimai",]

lats_urls = [
            "https://www.e-latts.lv/alus-dzerieni.214.g",
            "https://www.e-latts.lv/alus-sidrs-un-kokteili.209.g",
            "https://www.e-latts.lv/bezalkoholiskias-alus-un-vins.207.g",
            "https://www.e-latts.lv/energijas-un-izotoniskie-dzerieni.208.g",
            "https://www.e-latts.lv/limonades-un-kvass.205.g",
            "https://www.e-latts.lv/stiprie-alkoholiskie-dzerieni.211.g",
            "https://www.e-latts.lv/sulas-nektari-un-sulu-dzerieni.206.g",
            "https://www.e-latts.lv/udens.204.g",
            "https://www.e-latts.lv/vini.210.g",]
words_to_remove = [
            'Alk.', 'Alko.', 'Alkoh.', 'Alkohol.', 'Alkoholi', 'Alkoholiskais', 
            'Alkoholiskias', 'Alkoholisks', 'Alus', 'Armanjaks', 'Arom.', 'B.', 
            'Baltv.', 'Baltvīns', 'Bezalk.', 'Brendijs', 'Dabīgais', 'Degv.', 
            'Dz.', 'Dzirkst.', 'Dzēriens', 'Džins', 'Enerģijas', 'Gāz.', 'Gāzēts', 
            'Karstvīns', 'Konjaks', 'Liķieris', 'Minerālūdens', 'Rozā', 'Rums', 
            'S.', 'Sark.', 'Sarkanv.', 'Sidrs', 'Stiprs', 'Tekila', 'Vermuts', 
            'Viegli', 'Viskijs', 'alk.', 'dz.', 'dzē.', 'dzēr.', 'dzēriens', 'k.', 
            'kok.', 'kokt.', 'kokteil.', 'kokteilis', 'minerālūd.', 'v.', 'vīns', 
            'Šampanietis', 'Ūdens', "CAN"]
word_mapping = {
            "baltvins": "Baltvīns",
            "sarkanvins": "Sarkanvīns",
            "roza-vins": "Rozā vīns",
            "auglu-vins": "Augļu vīns",
            "stiprinats-vins": "Stiprināts vīns",
            "sampanietis": "Šampanietis",
            "dzirkstosais-vins": "Dzirkstošais vīns",
            "alus": "Alus",
            "sidrs": "Sidrs",
            "kokteili": "Kokteiļi",
            "degvini": "Degvīns",
            "tekila": "Tekila",
            "dzins": "Džins",
            "brendijs": "Brendijs",
            "viskijs": "Viskijs",
            "kojaks": "Konjaks",
            "rums": "Rums",
            "balzams": "Balzāms",
            "likieris": "Liķieris",
            "vermuts": "Vermuts / aperitīvs",
            "sporta-un-funkcionālie-dzērieni": "Sporta dzērieni",
            "udens": "Ūdens",
            "limonades": "Limonādes",
            "sulas-un-sulu-dzerieni": "Sulas",
            "svaigas-sulas-smutiji": "Sulas",
            "sirupi": "Sīrupi / piedevas kokteiļiem",
            "bezalkoholiskais-alus": "Bezalkoholiskais alus",
            "bezalkoholiskais-sidrs": "Bezalkoholiskais sidrs",
            "bezalkoholiskais-vini": "Bezalkoholiskais vīni",
            "dzirkstosie-bezalkoholiskais-dzerieni": "Bezalkoholiskie dzērieni",
            "energijas-dzerieni": "Enerģijas dzērieni",}